services:
  - type: web
    name: saneamento-ceara-api
    env: python
    plan: free
    rootDir: saneamento-ceara-api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: saneamento-ceara-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO

databases:
  - name: saneamento-ceara-db
    databaseName: saneamento_ceara
    user: saneamento_user
    plan: free 