"""Initial migration with all tables

Revision ID: 712f2a9adea9
Revises: 
Create Date: 2025-07-30 08:31:20.804450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712f2a9adea9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('id_municipio', sa.String(length=7), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sigla_uf', sa.String(length=2), nullable=False),
    sa.Column('populacao_urbana_estimada_2022', sa.Integer(), nullable=True),
    sa.Column('populacao_total_estimada_2022', sa.Integer(), nullable=True),
    sa.Column('quantidade_sedes_agua', sa.Integer(), nullable=True),
    sa.Column('quantidade_sedes_esgoto', sa.Integer(), nullable=True),
    sa.Column('nome_prestador_predominante', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_municipio')
    )
    op.create_index(op.f('ix_municipios_id_municipio'), 'municipios', ['id_municipio'], unique=False)
    op.create_table('prestadores_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('natureza_juridica', sa.String(length=100), nullable=True),
    sa.Column('total_investido_historico', sa.Float(), nullable=True),
    sa.Column('media_arrecadacao_anual', sa.Float(), nullable=True),
    sa.Column('quantidade_municipios_atendidos', sa.Integer(), nullable=True),
    sa.Column('ano_primeiro_registro', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sigla')
    )
    op.create_index(op.f('ix_prestadores_servico_id'), 'prestadores_servico', ['id'], unique=False)
    op.create_table('indicadores_desempenho_anuais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.String(length=7), nullable=False),
    sa.Column('prestador_id', sa.Integer(), nullable=False),
    sa.Column('populacao_atendida_agua', sa.Integer(), nullable=True),
    sa.Column('populacao_atendida_esgoto', sa.Integer(), nullable=True),
    sa.Column('indice_atendimento_agua', sa.Float(), nullable=True),
    sa.Column('indice_coleta_esgoto', sa.Float(), nullable=True),
    sa.Column('indice_tratamento_esgoto', sa.Float(), nullable=True),
    sa.Column('indice_perda_faturamento', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id_municipio'], ),
    sa.ForeignKeyConstraint(['prestador_id'], ['prestadores_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'municipio_id', 'prestador_id', name='uq_ano_municipio_prestador')
    )
    op.create_index('idx_ano', 'indicadores_desempenho_anuais', ['ano'], unique=False)
    op.create_index('idx_municipio_ano', 'indicadores_desempenho_anuais', ['municipio_id', 'ano'], unique=False)
    op.create_index('idx_prestador_ano', 'indicadores_desempenho_anuais', ['prestador_id', 'ano'], unique=False)
    op.create_index(op.f('ix_indicadores_desempenho_anuais_id'), 'indicadores_desempenho_anuais', ['id'], unique=False)
    op.create_table('financeiro_anuais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=False),
    sa.Column('receita_operacional_total', sa.Float(), nullable=True),
    sa.Column('despesa_exploracao', sa.Float(), nullable=True),
    sa.Column('despesa_pessoal', sa.Float(), nullable=True),
    sa.Column('despesa_energia', sa.Float(), nullable=True),
    sa.Column('despesa_total_servicos', sa.Float(), nullable=True),
    sa.Column('investimento_total_prestador', sa.Float(), nullable=True),
    sa.Column('credito_a_receber', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicadores_desempenho_anuais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicador_id')
    )
    op.create_index(op.f('ix_financeiro_anuais_id'), 'financeiro_anuais', ['id'], unique=False)
    op.create_table('recursos_hidricos_anuais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=False),
    sa.Column('volume_agua_produzido', sa.Float(), nullable=True),
    sa.Column('volume_agua_consumido', sa.Float(), nullable=True),
    sa.Column('volume_agua_faturado', sa.Float(), nullable=True),
    sa.Column('volume_esgoto_coletado', sa.Float(), nullable=True),
    sa.Column('volume_esgoto_tratado', sa.Float(), nullable=True),
    sa.Column('consumo_eletrico_sistemas_agua', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicadores_desempenho_anuais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicador_id')
    )
    op.create_index(op.f('ix_recursos_hidricos_anuais_id'), 'recursos_hidricos_anuais', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recursos_hidricos_anuais_id'), table_name='recursos_hidricos_anuais')
    op.drop_table('recursos_hidricos_anuais')
    op.drop_index(op.f('ix_financeiro_anuais_id'), table_name='financeiro_anuais')
    op.drop_table('financeiro_anuais')
    op.drop_index(op.f('ix_indicadores_desempenho_anuais_id'), table_name='indicadores_desempenho_anuais')
    op.drop_index('idx_prestador_ano', table_name='indicadores_desempenho_anuais')
    op.drop_index('idx_municipio_ano', table_name='indicadores_desempenho_anuais')
    op.drop_index('idx_ano', table_name='indicadores_desempenho_anuais')
    op.drop_table('indicadores_desempenho_anuais')
    op.drop_index(op.f('ix_prestadores_servico_id'), table_name='prestadores_servico')
    op.drop_table('prestadores_servico')
    op.drop_index(op.f('ix_municipios_id_municipio'), table_name='municipios')
    op.drop_table('municipios')
    # ### end Alembic commands ###
